version: 2.0
jobs:
  build:
    docker:
      - image: membrane/membrane:latest
    working_directory: ~/app
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix deps.get
      - run: MIX_ENV=dev mix docs && mix docs 2>&1 | (! grep -q "warning:")
      - persist_to_workspace:
          root: .
          paths: doc
  deploy-doc:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "78:41:d6:8c:c1:2d:ff:f4:30:40:d1:a3:26:9a:67:f5"
      - attach_workspace:
          at: /tmp/app
      - run:
          name: "Deploy 'doc' over SSH"
          command: |
            rsync -av --delete -e "ssh -p $SSH_PORT" /tmp/app/doc/ $SSH_USER@$SSH_HOST:$SSH_PATH/guide/$CIRCLE_BRANCH/
  deploy-landing:
    machine:
      enabled: true
    working_directory: ~/app
    steps:
      - add_ssh_keys:
          fingerprints:
            - "78:41:d6:8c:c1:2d:ff:f4:30:40:d1:a3:26:9a:67:f5"
      - checkout
      - run:
          name: "Deploy 'landing' over SSH"
          command: |
            scp -P $SSH_PORT landing/* $SSH_USER@$SSH_HOST:$SSH_PATH/guide/

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy-doc:
          requires:
            - build
          filters:
            branches:
              only:
                - /v[0-9]+\.[0-9]+(-dev)?/
      - deploy-landing:
          filters:
            branches:
              only: master
